-dontobfuscate
-dontoptimize
-dontpreverify
-dontnote
-dontwarn
-ignorewarnings
-keepattributes

-keepclasseswithmembers public class * {
    public static void main(java.lang.String[]);
}
-keepclass class processing.core.PGraphicsJava2D
-keepclassmembers class processing.core.PGraphics2D
-keepclassmembernames class processing.core.PGraphics2D
-keepclasseswithmembers class processing.core.PGraphics2D

-keep class * implements org.xml.sax.EntityResolver

-keepclassmembers class * {
    ** MODULE$;
}

-keepclassmembernames class scala.concurrent.forkjoin.ForkJoinPool {
    long eventCount;
    int  workerCounts;
    int  runControl;
    scala.concurrent.forkjoin.ForkJoinPool$WaitQueueNode syncStack;
    scala.concurrent.forkjoin.ForkJoinPool$WaitQueueNode spareStack;
}

-keepclassmembernames class scala.concurrent.forkjoin.ForkJoinWorkerThread {
    int base;
    int sp;
    int runState;
}

-keepclassmembernames class scala.concurrent.forkjoin.ForkJoinTask {
    int status;
}

-keepclassmembernames class scala.concurrent.forkjoin.LinkedTransferQueue {
    scala.concurrent.forkjoin.LinkedTransferQueue$PaddedAtomicReference head;
    scala.concurrent.forkjoin.LinkedTransferQueue$PaddedAtomicReference tail;
    scala.concurrent.forkjoin.LinkedTransferQueue$PaddedAtomicReference cleanMe;
}


-keep class java.awt.event.MouseWheelEvent
-keep class java.awt.event.MouseWheelListener
-keep class java.awt.event.MouseListener
-keep class org.processing.core.PApplet
-keep class processing.pdf.PGraphicsPDF
-keep class eu.tinasoft.tinaviz.scene.TApplet
